# Generated by Django 4.2.1 on 2023-06-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_useraccount_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
